
package vistas;

import Entidades.Alumno;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Grupo 3
 */
public class FormularioAlumnos extends javax.swing.JInternalFrame {
        DefaultTableModel modelo = new DefaultTableModel();
        public static HashSet<Alumno>alumnos;
    public FormularioAlumnos() {
        alumnos = new HashSet<>();
        initComponents();
        armarCabecera();
        cargarTabla();
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTLegajo = new javax.swing.JTextField();
        jTApellido = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jBSalirAL = new javax.swing.JButton();
        jBGuardarAL = new javax.swing.JButton();
        jBNuevoAL = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAlumnos = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de Alumnos");

        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Legajo: ");

        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Apellido:");

        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Nombre:");

        jBSalirAL.setForeground(new java.awt.Color(0, 102, 255));
        jBSalirAL.setText("Salir");

        jBGuardarAL.setForeground(new java.awt.Color(0, 102, 255));
        jBGuardarAL.setText("Guardar");
        jBGuardarAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarALActionPerformed(evt);
            }
        });

        jBNuevoAL.setForeground(new java.awt.Color(0, 102, 255));
        jBNuevoAL.setText("Nuevo");
        jBNuevoAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoALActionPerformed(evt);
            }
        });

        jTAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTAlumnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTNombre)
                                .addComponent(jTApellido)
                                .addComponent(jTLegajo)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jBGuardarAL)
                            .addGap(57, 57, 57)
                            .addComponent(jBNuevoAL)
                            .addGap(55, 55, 55)
                            .addComponent(jBSalirAL)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardarAL)
                    .addComponent(jBNuevoAL)
                    .addComponent(jBSalirAL))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarALActionPerformed
        try{
           int legajo = Integer.parseInt(jTLegajo.getText());
           String apellido = jTApellido.getText();
           String nombre = jTNombre.getText();
           int confirmacion = JOptionPane.showInternalConfirmDialog(this, "¿los datos ingresados son correcto?");
           if (confirmacion == JOptionPane.YES_OPTION) {
               Alumno nuevoAlumno = new Alumno(legajo, apellido, nombre);
               alumnos.add(nuevoAlumno);
               cargarTabla();
           } else {
               JOptionPane.showMessageDialog(this, "Porfavor vuelva a cargar los datos");
               jTLegajo.setText("");
               jTApellido.setText("");
               jTNombre.setText("");
           }
        }catch(NumberFormatException  ex){
          JOptionPane.showMessageDialog(this, "La matricula debe ser un numero");
        }
    }//GEN-LAST:event_jBGuardarALActionPerformed

    private void jBNuevoALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoALActionPerformed
//        try{
//           int legajo = Integer.parseInt(jTLegajo.getText());
//           String apellido = jTApellido.getText();
//           String nombre = jTNombre.getText();
//           Alumno nuevoAlumno = new Alumno(legajo, apellido, nombre);
//           alumnos.add(nuevoAlumno);
//           cargarTabla();
           jTLegajo.setText("");
           jTApellido.setText("");
           jTNombre.setText("");
//        }catch(NumberFormatException  ex){
//         JOptionPane.showMessageDialog(this, "La matricula debe ser un numero");
//    }
    }//GEN-LAST:event_jBNuevoALActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardarAL;
    private javax.swing.JButton jBNuevoAL;
    private javax.swing.JButton jBSalirAL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTAlumnos;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTLegajo;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
private void armarCabecera(){
    modelo.addColumn("LEGAJO");
    modelo.addColumn("APELLIDO");
    modelo.addColumn("NOMBRE");
    jTAlumnos.setModel(modelo);
}
private void cargarTabla(){
    modelo.setRowCount(0);
    for (Alumno alumno : alumnos) {
        modelo.addRow(new Object[]{
            alumno.getLegajo(),
            alumno.getApellido(),
            alumno.getNombre()
        });
    }
}
}
