/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Materia;
import static Vistas.VistaPrincipal.MATERIAS;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ezequiel
 */
public class jIFagregarMateria extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form jIFagregarAlumno
     */
    public jIFagregarMateria() {
        initComponents();
        this.agregarColumnas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLFormulariodeMaterias = new javax.swing.JLabel();
        jLcodigodemateria = new javax.swing.JLabel();
        jLnombredeMateria = new javax.swing.JLabel();
        jlAñodeMateria = new javax.swing.JLabel();
        jTFcodigodeMateria = new javax.swing.JTextField();
        jTFnombredeMateria = new javax.swing.JTextField();
        jTFAñodelaMateria = new javax.swing.JTextField();
        jBguardar = new javax.swing.JButton();
        jBnuevo = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMaterias = new javax.swing.JTable();

        jLFormulariodeMaterias.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLFormulariodeMaterias.setForeground(new java.awt.Color(0, 102, 255));
        jLFormulariodeMaterias.setText("Formulario de materias");

        jLcodigodemateria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLcodigodemateria.setForeground(new java.awt.Color(0, 102, 255));
        jLcodigodemateria.setText("Codigo de materia:");

        jLnombredeMateria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLnombredeMateria.setForeground(new java.awt.Color(0, 102, 255));
        jLnombredeMateria.setText("Nombre de la materia:");

        jlAñodeMateria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlAñodeMateria.setForeground(new java.awt.Color(0, 102, 255));
        jlAñodeMateria.setText("Año al que pertenece:");

        jTFcodigodeMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcodigodeMateriaActionPerformed(evt);
            }
        });
        jTFcodigodeMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFcodigodeMateriaKeyTyped(evt);
            }
        });

        jTFnombredeMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnombredeMateriaActionPerformed(evt);
            }
        });

        jTFAñodelaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAñodelaMateriaActionPerformed(evt);
            }
        });

        jBguardar.setForeground(new java.awt.Color(0, 102, 255));
        jBguardar.setText("Guardar");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        jBnuevo.setForeground(new java.awt.Color(0, 102, 255));
        jBnuevo.setText("Nuevo");
        jBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActionPerformed(evt);
            }
        });

        jBsalir.setForeground(new java.awt.Color(0, 102, 255));
        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        jtMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtMaterias);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLFormulariodeMaterias))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLcodigodemateria)
                            .addComponent(jLnombredeMateria)
                            .addComponent(jlAñodeMateria))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFAñodelaMateria)
                            .addComponent(jTFnombredeMateria)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jTFcodigodeMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jBguardar)
                        .addGap(18, 18, 18)
                        .addComponent(jBnuevo)
                        .addGap(18, 18, 18)
                        .addComponent(jBsalir)
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addGap(54, 54, 54))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jLFormulariodeMaterias)
                .addGap(37, 37, 37)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcodigodemateria)
                    .addComponent(jTFcodigodeMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnombredeMateria)
                    .addComponent(jTFnombredeMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAñodeMateria)
                    .addComponent(jTFAñodelaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBguardar)
                    .addComponent(jBnuevo)
                    .addComponent(jBsalir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFcodigodeMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcodigodeMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcodigodeMateriaActionPerformed

    private void jTFnombredeMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnombredeMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnombredeMateriaActionPerformed

    private void jTFAñodelaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAñodelaMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAñodelaMateriaActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActionPerformed
        // TODO add your handling code here:
        jTFcodigodeMateria.setText("");
        jTFnombredeMateria.setText("");
        jTFAñodelaMateria.setText("");
    }//GEN-LAST:event_jBnuevoActionPerformed

    private void jTFcodigodeMateriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFcodigodeMateriaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcodigodeMateriaKeyTyped

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // TODO add your handling code here:
        try {
            MATERIAS.add(new Materia(Integer.parseInt(jTFcodigodeMateria.getText()), jTFnombredeMateria.getText(), Integer.parseInt(jTFAñodelaMateria.getText())));
            modelo.addRow(new Object[]{jTFcodigodeMateria.getText(), jTFnombredeMateria.getText(), jTFAñodelaMateria.getText()});
            JOptionPane.showMessageDialog(this, "Datos ingresados correctamente");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error al ingresar los datos");
        }
    }//GEN-LAST:event_jBguardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBnuevo;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLFormulariodeMaterias;
    private javax.swing.JLabel jLcodigodemateria;
    private javax.swing.JLabel jLnombredeMateria;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFAñodelaMateria;
    private javax.swing.JTextField jTFcodigodeMateria;
    private javax.swing.JTextField jTFnombredeMateria;
    private javax.swing.JLabel jlAñodeMateria;
    private javax.swing.JTable jtMaterias;
    // End of variables declaration//GEN-END:variables
    private void agregarColumnas() {
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Año");
        jtMaterias.setModel(modelo);
    }
}
