/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Alumno;
import Entidades.Materia;
import static Vistas.VistaPrincipal.ALUMNOS;
import static Vistas.VistaPrincipal.MATERIAS;
import javax.swing.JOptionPane;
/**
 *
 * @author Ezequiel
 */
public class jIFFormularioInscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form jIFagregarAlumno
     */
    public jIFFormularioInscripcion() {
        initComponents();
        this.cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLFormulariodeAlumno = new javax.swing.JLabel();
        jLlegajo = new javax.swing.JLabel();
        jLapellido = new javax.swing.JLabel();
        jBnuevo = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jCBmaterias = new javax.swing.JComboBox<>();
        jCBalumnos = new javax.swing.JComboBox<>();

        jLFormulariodeAlumno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLFormulariodeAlumno.setForeground(new java.awt.Color(0, 102, 255));
        jLFormulariodeAlumno.setText("Formulario de inscripción");

        jLlegajo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLlegajo.setForeground(new java.awt.Color(0, 102, 255));
        jLlegajo.setText("Elija una materia:");

        jLapellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLapellido.setForeground(new java.awt.Color(0, 102, 255));
        jLapellido.setText("Elija un alumno:");

        jBnuevo.setForeground(new java.awt.Color(0, 102, 255));
        jBnuevo.setText("Inscribir");
        jBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActionPerformed(evt);
            }
        });

        jBsalir.setForeground(new java.awt.Color(0, 102, 255));
        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        jCBmaterias.setModel(new javax.swing.DefaultComboBoxModel<>());
        jCBmaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBmateriasActionPerformed(evt);
            }
        });

        jCBalumnos.setModel(new javax.swing.DefaultComboBoxModel<>());
        jCBalumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBalumnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLlegajo)
                            .addComponent(jLapellido))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCBmaterias, 0, 142, Short.MAX_VALUE)
                            .addComponent(jCBalumnos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLFormulariodeAlumno)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jBnuevo)
                                .addGap(18, 18, 18)
                                .addComponent(jBsalir)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLFormulariodeAlumno)
                .addGap(31, 31, 31)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLlegajo)
                    .addComponent(jCBmaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLapellido)
                    .addComponent(jCBalumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBnuevo)
                    .addComponent(jBsalir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Agregado correctamente");
    }//GEN-LAST:event_jBnuevoActionPerformed

    private void jCBmateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBmateriasActionPerformed
        // TODO add your handling code here:
        Materia materiaSeleccionada  = (Materia) jCBmaterias.getSelectedItem();
        materiaSeleccionada.toString();
    }//GEN-LAST:event_jCBmateriasActionPerformed

    private void jCBalumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBalumnosActionPerformed
        // TODO add your handling code here:
                                         
        Alumno alumnoSelecionado = (Alumno) jCBalumnos.getSelectedItem();
        alumnoSelecionado.toString();
                                               

    }//GEN-LAST:event_jCBalumnosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBnuevo;
    private javax.swing.JButton jBsalir;
    private javax.swing.JComboBox<Alumno> jCBalumnos;
    private javax.swing.JComboBox<Materia> jCBmaterias;
    private javax.swing.JLabel jLFormulariodeAlumno;
    private javax.swing.JLabel jLapellido;
    private javax.swing.JLabel jLlegajo;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
    private void cargarCombo(){
        for (Alumno alumno : ALUMNOS) {
            jCBalumnos.addItem(alumno);
        }
        for (Materia materia : MATERIAS) {
            jCBmaterias.addItem(materia);
        }
    }
}
